name: 'Gemini Hello World'

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
    - name: Install Gemini CLI
      run: npm install -g @google/gemini-cli
    - name: Run Gemini Hello
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        if [ -z "$GEMINI_API_KEY" ]; then
          echo "GEMINI_API_KEY is not set. Please set it as a repository secret."
          exit 1
        fi
        gemini -p hello
