name: ShellCheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run ShellCheck on bot scripts
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: '.'
        format: gcc
        severity: warning
        exclude_paths: |
          .git
          .github
          tweet.sh
        additional_files: '*.sh'
      env:
        SHELLCHECK_OPTS: -e SC1091 -e SC2034 -e SC2155 -e SC2166 -e SC2196 -e SC2001