name: Shell Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shfmt:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install shfmt
      run: |
        SHFMT_VERSION=$(curl -s https://api.github.com/repos/mvdan/sh/releases/latest | grep tag_name | cut -d '"' -f 4)
        curl -L "https://github.com/mvdan/sh/releases/latest/download/shfmt_${SHFMT_VERSION}_linux_amd64" -o shfmt
        chmod +x shfmt
        sudo mv shfmt /usr/local/bin/
        
    - name: Check shell script formatting
      run: |
        # Find all .sh files except tweet.sh (external code)
        find . -name "*.sh" ! -name "tweet.sh" ! -path "./.git/*" ! -path "./.github/*" -print0 | \
        xargs -0 shfmt -d -i 2 -ci -sr